### ISSUE TITLE
Cooperation?

### ISSUE THREAD

**Issue by szabgab** [benmvp/frontend-confs#1]
Hi Ben,

would you like to cooperate building the https://codeandtalk.com/ site?

**Comment by benmvp** [comment]
Hey Gabor! I've actually been using your site as a resource! I'd love to help, but bandwidth is tight, which is why I went the quick and dirty route of making a README. 

However I just found https://github.com/prigara/javascript-conferences and it seems to be getting lots of traction, so I may just contribute to hers...

**Comment by szabgab** [comment]
My hope was that you will start contributing to mine: https://github.com/szabgab/codeandtalk.com and then we could generate the view you prefer to have on the data.
I have this now: https://codeandtalk.com/t/frontend
Once I can get you to join the effort maybe I can get her too 😸

**Comment by szabgab** [comment]
/Once/If/

**Comment by PavloKovalov** [comment]
Looks like you are not alone! 
I'm contributing from time to time here: https://github.com/frontendfront/front-end-conferences, from which http://frontendfront.com/conferences build.

**Comment by benmvp** [comment]
So sorry for the delay in responding. I think for now I'll keep going with this simple repo due to the targeted nature of frontend conferences for speaking. In an ideal world I'd also add to your repo, but realistically I don't think I'll have the time to do it. 😞
